name: Build

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - name: clean install dependencies
        run: npm ci

      - name: Install VSCE
        run: npm install -g vsce

      - name: compile and create vsix
        run: npm run package
